version: "3.9"
services:
  db:
    image: circleci/mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql/data
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: realvtuber_test
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment: 
      RAILS_ENV: test
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db